#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
