#!/usr/bin/env bash
#config a new server

sudo apt-get update
sudo apt-get install nginx
sudo service nginx start
sed -i "/listen 80 default_server/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sudo service nginx restart
