#!/usr/bin/env bash
#install haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sed -i "$ a frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" /etc/haproxy/haproxy.cfg
sed -i "$ a backend http_back\n\tbalance roundrobin\n\tserver ubuntu 35.237.143.111:80 check\n\tserver ubuntu 34.227.206.85:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
