#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

cp /etc/hosts ~/temporal
sed -i 's/127.0.0.1/127.0.0.2/g' ~/temporal
echo "8.8.8.8	facebook.com" >> ~/temporal
cp -f ~/temporal /etc/hosts
